name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    permissions:
      # Required to checkout the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install Dependencies
        run: bun i

      - name: Build Check
        env:
          NODE_ENV: production
        run: bun run build

      - name: Run Lint Check
        run: bun run lint

      - name: Run Unit Tests
        run: bun run test

      - name: 'Test'
        run: npx vitest --coverage
      
      - name: 'Report Coverage'
        if: always()
        uses:  davelosert/vitest-coverage-report-action@v1
